require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-faker
inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/routes.rb'
    - 'config/environments/*'
    - db/schema.rb